GermanyEuro2024_RazorPage/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GermanyEuro2024_RazorPage.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

GermanyEuro2024_RazorPage/Pages/FootballManagement.cshtml.cs
using System.Text.RegularExpressions;
using GermanyEuro2024_BusinessObject;
using GermanyEuro2024_Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GermanyEuro2024_RazorPage.Pages;

public class FootballManagement : PageModel
{
    private readonly IFootballPlayerRepository _footballPlayerRepository;
    private readonly IFootballTeamRepository _footballTeamRepository;

    public FootballManagement(IFootballPlayerRepository footballPlayerRepository, IFootballTeamRepository footballTeamRepository)
    {
        _footballPlayerRepository = footballPlayerRepository;
        _footballTeamRepository = footballTeamRepository;
    }
    [BindProperty]
    public FootballPlayer SelectedFootballPlayer { get; set; }
    
    public List<FootballPlayer> FootballPlayers { get; set; }
    
    public List<FootballTeam> FootballTeams { get; set; }
    
    public List<SelectListItem> Teams { get; set; }
    
    public string UserRole{ get; private set; }
    
    public void OnGet()
    {
        UserRole = HttpContext.Session.GetString("UserRole");
        var players = _footballPlayerRepository.GetFootballPlayerList();
        FootballPlayers = players;
        
        var footballTeams = _footballTeamRepository.GetAllTeams();
        Teams = footballTeams.Select(t => new SelectListItem
        {
            Value = t.FootballTeamId,
            Text = t.TeamTitle
        }).ToList();
    }

    public IActionResult OnPostLogout()
    {
        HttpContext.Session.Remove("UserRole");
        return RedirectToPage("/Index");
    }
    public void OnPostSelect(string footballPlayerId)
    {
        UserRole = HttpContext.Session.GetString("UserRole");

        SelectedFootballPlayer = _footballPlayerRepository.GetFootballPlayerById(footballPlayerId);
            var footballTeams = _footballTeamRepository.GetAllTeams();
            Teams = footballTeams.Select(t => new SelectListItem
            {
                Value = t.FootballTeamId,
                Text = t.TeamTitle
            }).ToList();
            FootballPlayers = _footballPlayerRepository.GetFootballPlayerList();

    }

    public string GetFootballTeam(string footballTeamId)
    {
        var team = FootballTeams.FirstOrDefault(t => t.FootballTeamId == footballTeamId);
        return team != null ? team.TeamTitle : "Unknown";
    }

    public void LoadDataInit()
    {
        SelectedFootballPlayer.PlayerId = "";
        SelectedFootballPlayer.PlayerName = "";
        SelectedFootballPlayer.FootballTeamId = "";
        SelectedFootballPlayer.Achievements = "";
        SelectedFootballPlayer.Award = "";
        SelectedFootballPlayer.Birthday = null;
        SelectedFootballPlayer.OriginCountry = "";
        
        FootballPlayers = _footballPlayerRepository.GetFootballPlayerList();
        var footballTeams = _footballTeamRepository.GetAllTeams();
        Teams = footballTeams.Select(t => new SelectListItem
        {
            Value = t.FootballTeamId,
            Text = t.TeamTitle
        }).ToList();
        RedirectToPage("FootballManagement");
        
    }

    public IActionResult OnPostClear()
    {
        LoadDataInit();
        return RedirectToPage("FootballManagement");
    }

    public IActionResult OnPostAdd()
    {
        try
        {
            FootballPlayer newFootballPlayer = new FootballPlayer();
            newFootballPlayer.PlayerId = GetNewId();
            newFootballPlayer.PlayerName = SelectedFootballPlayer.PlayerName;
            if (!isValidName(SelectedFootballPlayer.PlayerName))
            {
                TempData["Error"] = "Please enter a valid name";
                LoadDataInit();
                return OnPostClear();
            }
            newFootballPlayer.Birthday = SelectedFootballPlayer.Birthday;
            if (SelectedFootballPlayer.Birthday > new DateTime(2004, 1, 1))
            {
                TempData["Error"] = "We don't accept players younger than 2004";
                LoadDataInit();
                return OnPostClear();
            }
            newFootballPlayer.Achievements = SelectedFootballPlayer.Achievements;
            newFootballPlayer.Award = SelectedFootballPlayer.Award;
            newFootballPlayer.OriginCountry = SelectedFootballPlayer.OriginCountry;
            newFootballPlayer.FootballTeamId = SelectedFootballPlayer.FootballTeamId;
            _footballPlayerRepository.AddFootballPlayer(newFootballPlayer);
            SelectedFootballPlayer = new FootballPlayer();
            LoadDataInit();
            FootballPlayers = _footballPlayerRepository.GetFootballPlayerList();
            TempData["SuccessMessage"] = "Add player successfully.";
            
        }
        catch (Exception ex)
        {
            ModelState.AddModelError("", "Error adding player: " + ex.Message);
            FootballPlayers = _footballPlayerRepository.GetFootballPlayerList();
        }
        return OnPostClear();
    }
    private string GetNewId()
    {
        List<FootballPlayer> footballPlayers = _footballPlayerRepository.GetFootballPlayerList();
        FootballPlayer lastFootballPlayer = footballPlayers.OrderBy(p => p.PlayerId).LastOrDefault();
        int number =  int.Parse(lastFootballPlayer.PlayerId.Substring(2)) + 1;
        return $"PL{number:D5}";
    }

    private bool isValidName(string name)
    {
        var result = !(name.Length < 3 || name.Length > 100);
        if (!Regex.IsMatch(name, @"^[A-Za-z0-9 ]+$"))
        {
            result = false;
        }
        string[] words = name.Split(' ');
        foreach (string word in words)
        {
            if (!Regex.IsMatch(word, @"^[A-Z0-9]"))
            {
                result = false;
            }
        }
        return result;
    }

    public IActionResult OnPostDelete()
    {
            _footballPlayerRepository.RemoveFootballPlayer(SelectedFootballPlayer.PlayerId);
            TempData["SuccessMessage"] = "Delete player successfully.";
            return OnPostClear();
            
    }

    public IActionResult OnPostUpdate()
    {
        FootballPlayer updateFootballPlayer = _footballPlayerRepository.GetFootballPlayerById(SelectedFootballPlayer.PlayerId);
        updateFootballPlayer.PlayerName = SelectedFootballPlayer.PlayerName;
        if (!isValidName(SelectedFootballPlayer.PlayerName))
        {
            TempData["Error"] = "Please enter a valid name";
            LoadDataInit();
            return Page();
        }
        updateFootballPlayer.Birthday = SelectedFootballPlayer.Birthday;
        if (SelectedFootballPlayer.Birthday > new DateTime(2004, 1, 1))
        {
            TempData["Error"] = "We don't accept players younger than 2004";
            LoadDataInit();
            return Page();
        }
        updateFootballPlayer.Achievements = SelectedFootballPlayer.Achievements;
        updateFootballPlayer.Award = SelectedFootballPlayer.Award;
        updateFootballPlayer.OriginCountry = SelectedFootballPlayer.OriginCountry;
        updateFootballPlayer.FootballTeamId = SelectedFootballPlayer.FootballTeamId;
        _footballPlayerRepository.UpdateFootballPlayer(updateFootballPlayer);
        SelectedFootballPlayer = new FootballPlayer();
        FootballPlayers = _footballPlayerRepository.GetFootballPlayerList();
        TempData["SuccessMessage"] = "Update player successfully.";
        LoadDataInit();
        return RedirectToPage("FootballManagement");
            
    }
    
    public IActionResult OnPostSearch(string searchTerm, string searchBy)
    {
        var players = _footballPlayerRepository.GetFootballPlayerList();
        if (!string.IsNullOrEmpty(searchTerm))
        {
            if (searchBy == "name")
            {
                FootballPlayers = _footballPlayerRepository.FindFootballPlayersByName(searchTerm);
            }
            else if (searchBy == "achievement")
            {
                FootballPlayers = _footballPlayerRepository.FindFootballPlayersByAchievements(searchTerm);
            }
        }
        else
        {
           FootballPlayers = players;
        }

        return Page();
    }
   
}

GermanyEuro2024_RazorPage/Pages/Index.cshtml.cs
using GermanyEuro2024_BusinessObject;
using GermanyEuro2024_Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace GermanyEuro2024_RazorPage.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly IUefaAccountRepository _uefaAccountRepository;
    public IndexModel(ILogger<IndexModel> logger,IUefaAccountRepository uefaAccountRepository)
    {
        _logger = logger;
      
        _uefaAccountRepository = uefaAccountRepository;

    }
    
    [BindProperty]
    public string Email { get; set; }
    [BindProperty]
    public string Password { get; set; }
    
    public string ErrorMessage { get; set; }

    public IActionResult OnPost()
    {
        Uefaaccount uefaAccount = _uefaAccountRepository.GetUEFAAccountByEmail(Email);

        if (uefaAccount != null && uefaAccount.AccountPassword == Password)
        {
            HttpContext.Session.SetString("UserRole", uefaAccount.Role.ToString());
            return RedirectToPage("/FootballManagement");
        }
        else
        {
            ErrorMessage = "Invalid email or password";
            return Page();
        }
    }
}

GermanyEuro2024_RazorPage/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GermanyEuro2024_RazorPage.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

GermanyEuro2024_RazorPage/Pages/FootballManagement.cshtml
@page
@model GermanyEuro2024_RazorPage.Pages.FootballManagement
@{
    ViewData["Title"] = "Football Player Management";
}
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["SuccessMessage"]
    </div>
}
@if (TempData["Error"] != null)
{
    <div class="alert alert-warning" role="alert">
        @TempData["Error"]
    </div>
}
@{
    Layout = null;
}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>@ViewData["Title"]</title>
</head>
<body>
@if (Model.UserRole is "1" or "4")
{
    <div class="alert alert-danger" role="alert">
        You have no permission to access this function!
    </div>
    <form method="post">
        <button type="submit" asp-page-handler="Logout">Come Back</button>
    </form>
}
else
{
    
    <div class="p-3 mb-2 bg-dark-subtle">
        <form method="post">
            <button type="submit" asp-page-handler="Logout">Logout</button>
        </form>
        
        <h1>Football Management</h1>

        <form method="post" class="row g-3">

            <div class="col-md-6">
                <label for="playerId" class="form-label">Player ID</label>
                <input type="text" id="playerId" asp-for="SelectedFootballPlayer.PlayerId" readonly="" class="form-control"/>
            </div>
            <div class="col-md-6">
                <label for="playerName" class="form-label">Player Name</label>
                <input type="text" id="playerName" asp-for="SelectedFootballPlayer.PlayerName" class="form-control"/>
            </div>
            <div class="col-md-6">
                <label for="birthday" class="form-label">Birthday</label>
                <input type="date" id="birthday" asp-for="SelectedFootballPlayer.Birthday" class="form-control"/>
            </div>
            <div class="col-md-6">
                <label for="award" class="form-label">Award</label>
                <input type="text" id="award" asp-for="SelectedFootballPlayer.Award" class="form-control"/>
            </div>
            <div class="col-12">
                <label for="achievement" class="form-label">Achievements</label>
                <input id="achievement" asp-for="SelectedFootballPlayer.Achievements" class="form-control"/>
            </div>
            <div class="col-md-6">
                <label for="country" class="form-label">Original Country</label>
                <input type="text" id="country" asp-for="SelectedFootballPlayer.OriginCountry" class="form-control"/>
            </div>
            <div class="col-md-6">
                <label for="teamTitle" class="form-label">Football Team</label>
                <select id="teamTitle" asp-for="SelectedFootballPlayer.FootballTeamId" asp-items="Model.Teams" class="form-select">
                    <option selected>Select Team</option>
                </select>
            </div>
            <div>
                <button type="submit" class="btn btn-outline-success" asp-page-handler="Add" disabled="@(Model.UserRole != "3")">Add</button>
                <button type="submit" class="btn btn-outline-warning" asp-page-handler="Update" disabled="@(Model.UserRole != "3")">Update</button>
                <button type="submit" class="btn btn-outline-danger" asp-page-handler="Delete" disabled="@(Model.UserRole != "3")" onclick="return confirm('Are you sure you want to delete this player?');">Delete</button>
                <button type="submit" class="btn btn-outline-info" asp-page-handler="Clear">Clear</button>
            </div>
        </form>

        <form method="post" asp-page-handler="Search">
            <div class="input-group">
                <select class="form-select" name="searchBy">
                    <option value="name">By Name</option>
                    <option value="achievement">By Achievement</option>
                </select>
                <div class="form-floating">
                    <input type="text" name="searchTerm" id="searchTerm" class="form-control" placeholder="name@example.com"/>
                    <label for="searchTerm">Search</label>
                </div>

                <button type="submit" class="btn btn-outline-secondary">Search</button>
            </div>
        </form>

        <div>
            <table border="1" class="table table-striped table-dark">
                <thead>
                <tr>
                    <th scope="col">Player ID</th>
                    <th scope="col">Player Name</th>
                    <th scope="col">Achievements</th>
                    <th scope="col">Birthday</th>
                    <th scope="col">Country</th>
                    <th scope="col">Award</th>
                    <th scope="col">Football Team</th>
                    <th scope="col">Select</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var player in Model.FootballPlayers)
                {
                    <tr>
                        <th scope="row">@player.PlayerId</th>
                        <td>@player.PlayerName</td>
                        <td>@player.Achievements</td>
                        <td>@player.Birthday</td>
                        <td>@player.OriginCountry</td>
                        <td>@player.Award</td>
                        <td>@player.FootballTeam?.TeamTitle</td>

                        <td>
                            <form method="post" asp-page-handler="Select">
                                <input type="hidden" name="footballPlayerId" value="@player.PlayerId"/>
                                <button type="submit" class="btn btn-outline-light">Select</button>
                            </form>
                        </td>
                    </tr>
                }
                </tbody>
            </table>


        </div>

    </div>
}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

GermanyEuro2024_RazorPage/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Login page";
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>@ViewData["Title"]</title>

</head>
<body>
<div>

    <div class="card p-4 shadow " style="width: 100%; max-width: 400px; margin-left: 30%;">
        <h2 class="text-center mb-4">Sign In</h2>
        <form method="post">
            <div class="form-floating mb-3">
                <input type="email" id="email" name="email" class="form-control" placeholder="example@gmail.com"/>
                <label for="email">Email</label>
            </div>

            <div class="form-floating mb-4">
                <input type="password" id="password" name="password" class="form-control" placeholder="Password"/>
                <label for="password">Password</label>
            </div>

            <button type="submit" class="btn btn-primary btn-block w-100">Sign in</button>
        </form>
    </div>

    @* <div class="tab-content"> *@
    @*     <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login"> *@
    @*         <form> *@
    @*             <div data-mdb-input-init class="form-outline mb-4"> *@
    @*                 <input type="email" id="email" name="email" class="form-control"/>  *@
    @*                 <label for="email" class="form-label">Email</label> *@
    @*             </div> *@
    @* *@
    @*             <div data-mdb-input-init class="form-outline mb-4"> *@
    @*                 <input type="password" id="password" class="form-control" /> *@
    @*                 <label class="form-label" for="password">Password</label> *@
    @*             </div> *@
    @* *@
    @*             <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Sign in</button> *@
    @*         </form> *@
    @*     </div> *@
    @* </div> *@

    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <div class="alert alert-danger">@Model.ErrorMessage</div>
}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>